site_name: Cloudmesh AI Theme Test
theme:
  name: material
  primary_color: "#ff0000"
  favicon: theme/assets/favicon.svg
  logo: theme/assets/logo-white.png
  palette:
    - scheme: default
      primary: "#ff0000"
      accent: "#ff0000"
    - scheme: slate
      primary: "#ff0000"
      accent: "#ff0000"

plugins:
  - search
  - cloudmesh-ai-theme
