site_name: Cloudmesh AI Theme
theme:
  name: material
  primary_color: "#ff0000"
  favicon: theme/assets/favicon.svg
  logo: theme/assets/logo-white.png
  palette:
    - scheme: default
      primary: "#ff0000"
      accent: "#ff0000"
    - scheme: slate
      primary: "#ff0000"
      accent: "#ff0000"

nav:
  - Home: index.md
  - Installation: installation.md
  - Development: development.md
  - Maintainer's Guide: maintainer.md

plugins:
  - search
  - cloudmesh-ai-theme
