[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cloudmesh-ai-theme"
dynamic = ["version"]
description = "Theme for Cloudmesh AI documentation"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "Apache-2.0" }
authors = [
  { name = "Cloudmesh AI Contributors" }
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]

dependencies = ["mkdocs"]

[project.urls]
Homepage = "https://github.com/cloudmesh/cloudmesh-ai-theme"

[project.entry-points."mkdocs.plugins"]
cloudmesh-ai-theme = "cloudmesh_ai_theme.plugin:CloudmeshAIThemePlugin"


[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "cloudmesh_ai_theme.__version__"}

[tool.setuptools.package-data]
cloudmesh_ai_theme = [
  "assets/*",
  "css/*",
  "theme/*",
  "theme.yml"
]
[tool.cloudmesh-ai]
category = "foundation"
status = "stable"
order = 30
